name: Advent of Code

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: mattdsteele/aoc-submit-action@main
        name: Advent Of Code
        env:
          AOC_SESSION_COOKIE: ${{ secrets.AOC_SESSION_COOKIE }}
          AOC_YEAR: ${{ secrets.AOC_YEAR }}
